system(['export FSLOUTPUTTYPE=NIFTI;' ...
    ...
    'flirt' ...
    ' -in ' PREPROC.anat_reference_file_masked ...
    ' -dof 12' ...
    ' -ref $FSLDIR/data/standard/MNI152_T1_2mm_brain.nii.gz' ...
    ' -omat ' fullfile(PREPROC.preproc_anat_dir, 'anat_reference_init_aff.mat')]);
system(['export FSLOUTPUTTYPE=NIFTI;' ...
    ...
    'fnirt' ...
    ' --in=' PREPROC.anat_reference_file ...
    ' --ref=$FSLDIR/data/standard/MNI152_T1_2mm.nii.gz' ...
    ' --refmask=$FSLDIR/data/standard/MNI152_T1_2mm_brain_mask_dil.nii.gz' ...
    ' --aff=' fullfile(PREPROC.preproc_anat_dir, 'anat_reference_init_aff.mat') ...
    ' --fout=' PREPROC.anat_reference_file_warpfield ...
    ' --logout=' fullfile(PREPROC.preproc_anat_dir, 'anat_reference_warping_diary.log') ...
    ' --config=$FSLDIR/etc/flirtsch/T1_2_MNI152_2mm.cnf']);
system(['export FSLOUTPUTTYPE=NIFTI;' ...
    ...
    'applywarp' ...
    ' --rel' ...
    ' --interp=trilinear' ...
    ' --in=' PREPROC.anat_reference_file ...
    ' --ref=$FSLDIR/data/standard/MNI152_T1_2mm.nii.gz' ...
    ' --warp=' PREPROC.anat_reference_file_warpfield ...
    ' --out=' PREPROC.anat_reference_file_warped]);
